apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: invoice-classifier-serving
  annotations:
    scenarios.ai.sap.com/name: "invoice-classification"
    scenarios.ai.sap.com/description: "Blocked invoice classification using DeBERTa-v3-base"
    executables.ai.sap.com/name: "invoice-classifier"
    executables.ai.sap.com/description: "Classify blocked invoices in SAP S/4HANA"
    artifacts.ai.sap.com/invoiceclassifiermodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "invoice-classification"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
      - name: invoiceclassifiermodel
    parameters:
      - name: serviceName
        type: string
        default: "invoice-classifier"
      - name: image
        type: string
        default: "docker.io/itsmarlo/invoice-serve:latest"
      - name: imagePullSecret
        type: string
        default: "docker-registry-secret"
      - name: port
        type: integer
        default: 8080
      - name: minReplicas
        type: integer
        default: 1
      - name: maxReplicas
        type: integer
        default: 3
      - name: resourcePlan
