apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: invoice-serving-pipeline
  annotations:
    scenarios.ai.sap.com/name: "Blocked Invoice Classification (BYOM)"
    scenarios.ai.sap.com/description: "Serve a Hugging Face model for blocked invoices"
    executables.ai.sap.com/name: "invoiceclassifierserving"
    executables.ai.sap.com/description: "Serving with blocked-invoice classifier"
    artifacts.ai.sap.com/invoiceclassifiermodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "blocked-invoice-classifier"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
      - name: invoiceclassifiermodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: serve.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 3
        containers:
        - name: kserve-container
          image: docker.io/itsmarlo/invoice-serve:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          command: ["/bin/sh","-c"]
          args:
            - >
              /app/serve.sh
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.invoiceclassifiermodel}}"
            - name: MODEL_PATH
              value: "/mnt/models"
            - name: PORT
              value: "8080"
