apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: invoice-classifier-serving
  annotations:
    scenarios.ai.sap.com/name: "invoice-classification"
    scenarios.ai.sap.com/description: "Blocked invoice classification using DeBERTa-v3-base"
    executables.ai.sap.com/name: "invoice-classifier"
    executables.ai.sap.com/description: "Classify blocked invoices"
    artifacts.ai.sap.com/invoiceclassifiermodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "invoice-classification"
    ai.sap.com/version: "1.0.0"

spec:
  inputs:
    artifacts:
      - name: invoiceclassifiermodel
    parameters:
      - name: image
        type: string
        default: docker.io/itsmarlo/invoice-serve:latest
      - name: resourcePlan
        type: string
        default: serve.s
      - name: port
        type: string
        default: "8080"
      # optional:
      - name: minReplicas
        type: string
        default: "1"
      - name: maxReplicas
        type: string
        default: "3"

  # IMPORTANT: 'template' must be a STRING containing the KServe InferenceService YAML
  template: |
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      n
