apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: invoice-training-pipeline
  annotations:
    scenarios.ai.sap.com/name: "Blocked Invoice Classification (BYOM)"
    scenarios.ai.sap.com/description: "Train a Hugging Face model for blocked invoices"
    executables.ai.sap.com/name: "Invoice model training"
    executables.ai.sap.com/description: "Training with blocked-invoice dataset"
    artifacts.ai.sap.com/invoicesdataset.kind: "dataset"
    artifacts.ai.sap.com/invoiceclassifiermodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "blocked-invoice-classifier"
    ai.sap.com/version: "1.0.0"

spec:
  imagePullSecrets:
    - name: docker-registry-secret
  entrypoint: mypipeline
  arguments:
    parameters:
      - name: BASE_MODEL
        value: "microsoft/deberta-v3-base"
      - name: NUM_EPOCHS
        value: "3"
      - name: LEARNING_RATE
        value: "2e-5"
      - name: BATCH_SIZE
        value: "16"
      - name: NUM_LABELS
        value: "5"

  templates:
    - name: mypipeline
      inputs:
        artifacts:
          - name: invoicesdataset
            path: /mnt/data/
      outputs:
        artifacts:
          - name: invoiceclassifiermodel
            globalName: invoiceclassifiermodel
            path: /mnt/models/
            archive:
              none: {}
      container:
  image: docker.io/itsmarlo/invoice-train:latest
  imagePullPolicy: Always
  command: ["/bin/bash", "-c"]
  env:
    - name: MODEL_NAME
      value: "{{workflow.parameters.BASE_MODEL}}"
    - name: NUM_EPOCHS
      value: "{{workflow.parameters.NUM_EPOCHS}}"
    - name: LEARNING_RATE
      value: "{{workflow.parameters.LEARNING_RATE}}"
    - name: BATCH_SIZE
      value: "{{workflow.parameters.BATCH_SIZE}}"
    - name: NUM_LABELS
      value: "{{workflow.parameters.NUM_LABELS}}"
    - name: DATA_PATH
      value: "/app/data"         
    - name: OUTPUT_DIR
      value: "/app/invoice_classifier"
  args:
    - |
      set -e
      echo "==== Starting Training ===="
      python /app/train.py        
      echo "==== Training Complete ===="
